// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ldl_dsolve_ldl_dsolve,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck24-ubva530-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=587,HLS_SYN_TPT=578,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=4660,HLS_SYN_LUT=5530,HLS_VERSION=2024_1}" *)

module ldl_dsolve (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (128 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;

 reg    ap_rst_n_inv;
wire   [31:0] n;
wire   [63:0] X;
wire   [63:0] D;
wire   [63:0] out_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [127:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [8:0] gmem0_RFIFONUM;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [127:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [8:0] gmem1_RFIFONUM;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [127:0] gmem2_RDATA;
wire   [8:0] gmem2_RFIFONUM;
wire    gmem2_BVALID;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_out_r_c_din;
wire    entry_proc_U0_out_r_c_write;
wire    read1_U0_ap_start;
wire    read1_U0_ap_done;
wire    read1_U0_ap_continue;
wire    read1_U0_ap_idle;
wire    read1_U0_ap_ready;
wire    read1_U0_start_out;
wire    read1_U0_start_write;
wire    read1_U0_m_axi_gmem0_AWVALID;
wire   [63:0] read1_U0_m_axi_gmem0_AWADDR;
wire   [0:0] read1_U0_m_axi_gmem0_AWID;
wire   [31:0] read1_U0_m_axi_gmem0_AWLEN;
wire   [2:0] read1_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] read1_U0_m_axi_gmem0_AWBURST;
wire   [1:0] read1_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] read1_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] read1_U0_m_axi_gmem0_AWPROT;
wire   [3:0] read1_U0_m_axi_gmem0_AWQOS;
wire   [3:0] read1_U0_m_axi_gmem0_AWREGION;
wire   [0:0] read1_U0_m_axi_gmem0_AWUSER;
wire    read1_U0_m_axi_gmem0_WVALID;
wire   [127:0] read1_U0_m_axi_gmem0_WDATA;
wire   [15:0] read1_U0_m_axi_gmem0_WSTRB;
wire    read1_U0_m_axi_gmem0_WLAST;
wire   [0:0] read1_U0_m_axi_gmem0_WID;
wire   [0:0] read1_U0_m_axi_gmem0_WUSER;
wire    read1_U0_m_axi_gmem0_ARVALID;
wire   [63:0] read1_U0_m_axi_gmem0_ARADDR;
wire   [0:0] read1_U0_m_axi_gmem0_ARID;
wire   [31:0] read1_U0_m_axi_gmem0_ARLEN;
wire   [2:0] read1_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] read1_U0_m_axi_gmem0_ARBURST;
wire   [1:0] read1_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] read1_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] read1_U0_m_axi_gmem0_ARPROT;
wire   [3:0] read1_U0_m_axi_gmem0_ARQOS;
wire   [3:0] read1_U0_m_axi_gmem0_ARREGION;
wire   [0:0] read1_U0_m_axi_gmem0_ARUSER;
wire    read1_U0_m_axi_gmem0_RREADY;
wire    read1_U0_m_axi_gmem0_BREADY;
wire   [127:0] read1_U0_X_stream_din;
wire    read1_U0_X_stream_write;
wire   [31:0] read1_U0_n_c1_din;
wire    read1_U0_n_c1_write;
wire    read2_U0_ap_start;
wire    read2_U0_ap_done;
wire    read2_U0_ap_continue;
wire    read2_U0_ap_idle;
wire    read2_U0_ap_ready;
wire    read2_U0_m_axi_gmem1_AWVALID;
wire   [63:0] read2_U0_m_axi_gmem1_AWADDR;
wire   [0:0] read2_U0_m_axi_gmem1_AWID;
wire   [31:0] read2_U0_m_axi_gmem1_AWLEN;
wire   [2:0] read2_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] read2_U0_m_axi_gmem1_AWBURST;
wire   [1:0] read2_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] read2_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] read2_U0_m_axi_gmem1_AWPROT;
wire   [3:0] read2_U0_m_axi_gmem1_AWQOS;
wire   [3:0] read2_U0_m_axi_gmem1_AWREGION;
wire   [0:0] read2_U0_m_axi_gmem1_AWUSER;
wire    read2_U0_m_axi_gmem1_WVALID;
wire   [127:0] read2_U0_m_axi_gmem1_WDATA;
wire   [15:0] read2_U0_m_axi_gmem1_WSTRB;
wire    read2_U0_m_axi_gmem1_WLAST;
wire   [0:0] read2_U0_m_axi_gmem1_WID;
wire   [0:0] read2_U0_m_axi_gmem1_WUSER;
wire    read2_U0_m_axi_gmem1_ARVALID;
wire   [63:0] read2_U0_m_axi_gmem1_ARADDR;
wire   [0:0] read2_U0_m_axi_gmem1_ARID;
wire   [31:0] read2_U0_m_axi_gmem1_ARLEN;
wire   [2:0] read2_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] read2_U0_m_axi_gmem1_ARBURST;
wire   [1:0] read2_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] read2_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] read2_U0_m_axi_gmem1_ARPROT;
wire   [3:0] read2_U0_m_axi_gmem1_ARQOS;
wire   [3:0] read2_U0_m_axi_gmem1_ARREGION;
wire   [0:0] read2_U0_m_axi_gmem1_ARUSER;
wire    read2_U0_m_axi_gmem1_RREADY;
wire    read2_U0_m_axi_gmem1_BREADY;
wire   [127:0] read2_U0_D_stream_din;
wire    read2_U0_D_stream_write;
wire    compute_U0_ap_start;
wire    compute_U0_ap_done;
wire    compute_U0_ap_continue;
wire    compute_U0_ap_idle;
wire    compute_U0_ap_ready;
wire    compute_U0_n_read;
wire    compute_U0_X_stream_read;
wire    compute_U0_D_stream_read;
wire   [127:0] compute_U0_X2_stream_din;
wire    compute_U0_X2_stream_write;
wire   [31:0] compute_U0_n_c_din;
wire    compute_U0_n_c_write;
wire    writeout_U0_ap_start;
wire    writeout_U0_ap_done;
wire    writeout_U0_ap_continue;
wire    writeout_U0_ap_idle;
wire    writeout_U0_ap_ready;
wire    writeout_U0_n_read;
wire    writeout_U0_X2_stream_read;
wire    writeout_U0_m_axi_gmem2_AWVALID;
wire   [63:0] writeout_U0_m_axi_gmem2_AWADDR;
wire   [0:0] writeout_U0_m_axi_gmem2_AWID;
wire   [31:0] writeout_U0_m_axi_gmem2_AWLEN;
wire   [2:0] writeout_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] writeout_U0_m_axi_gmem2_AWBURST;
wire   [1:0] writeout_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] writeout_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] writeout_U0_m_axi_gmem2_AWPROT;
wire   [3:0] writeout_U0_m_axi_gmem2_AWQOS;
wire   [3:0] writeout_U0_m_axi_gmem2_AWREGION;
wire   [0:0] writeout_U0_m_axi_gmem2_AWUSER;
wire    writeout_U0_m_axi_gmem2_WVALID;
wire   [127:0] writeout_U0_m_axi_gmem2_WDATA;
wire   [15:0] writeout_U0_m_axi_gmem2_WSTRB;
wire    writeout_U0_m_axi_gmem2_WLAST;
wire   [0:0] writeout_U0_m_axi_gmem2_WID;
wire   [0:0] writeout_U0_m_axi_gmem2_WUSER;
wire    writeout_U0_m_axi_gmem2_ARVALID;
wire   [63:0] writeout_U0_m_axi_gmem2_ARADDR;
wire   [0:0] writeout_U0_m_axi_gmem2_ARID;
wire   [31:0] writeout_U0_m_axi_gmem2_ARLEN;
wire   [2:0] writeout_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] writeout_U0_m_axi_gmem2_ARBURST;
wire   [1:0] writeout_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] writeout_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] writeout_U0_m_axi_gmem2_ARPROT;
wire   [3:0] writeout_U0_m_axi_gmem2_ARQOS;
wire   [3:0] writeout_U0_m_axi_gmem2_ARREGION;
wire   [0:0] writeout_U0_m_axi_gmem2_ARUSER;
wire    writeout_U0_m_axi_gmem2_RREADY;
wire    writeout_U0_m_axi_gmem2_BREADY;
wire    writeout_U0_X_final_read;
wire    out_r_c_full_n;
wire   [63:0] out_r_c_dout;
wire   [2:0] out_r_c_num_data_valid;
wire   [2:0] out_r_c_fifo_cap;
wire    out_r_c_empty_n;
wire    X_stream_full_n;
wire   [127:0] X_stream_dout;
wire   [2:0] X_stream_num_data_valid;
wire   [2:0] X_stream_fifo_cap;
wire    X_stream_empty_n;
wire    n_c1_full_n;
wire   [31:0] n_c1_dout;
wire   [2:0] n_c1_num_data_valid;
wire   [2:0] n_c1_fifo_cap;
wire    n_c1_empty_n;
wire    D_stream_full_n;
wire   [127:0] D_stream_dout;
wire   [2:0] D_stream_num_data_valid;
wire   [2:0] D_stream_fifo_cap;
wire    D_stream_empty_n;
wire    X2_stream_full_n;
wire   [127:0] X2_stream_dout;
wire   [2:0] X2_stream_num_data_valid;
wire   [2:0] X2_stream_fifo_cap;
wire    X2_stream_empty_n;
wire    n_c_full_n;
wire   [31:0] n_c_dout;
wire   [2:0] n_c_num_data_valid;
wire   [2:0] n_c_fifo_cap;
wire    n_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_read1_U0_ap_ready;
wire    ap_sync_read1_U0_ap_ready;
reg    ap_sync_reg_read2_U0_ap_ready;
wire    ap_sync_read2_U0_ap_ready;
wire   [0:0] start_for_writeout_U0_din;
wire    start_for_writeout_U0_full_n;
wire   [0:0] start_for_writeout_U0_dout;
wire    start_for_writeout_U0_empty_n;
wire   [0:0] start_for_compute_U0_din;
wire    start_for_compute_U0_full_n;
wire   [0:0] start_for_compute_U0_dout;
wire    start_for_compute_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read1_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read2_U0_ap_ready = 1'b0;
end

ldl_dsolve_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .n(n),
    .X(X),
    .D(D),
    .out_r(out_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

ldl_dsolve_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read1_U0_m_axi_gmem0_ARVALID),
    .I_CH0_ARREADY(gmem0_ARREADY),
    .I_CH0_ARADDR(read1_U0_m_axi_gmem0_ARADDR),
    .I_CH0_ARLEN(read1_U0_m_axi_gmem0_ARLEN),
    .I_CH0_RVALID(gmem0_RVALID),
    .I_CH0_RREADY(read1_U0_m_axi_gmem0_RREADY),
    .I_CH0_RDATA(gmem0_RDATA),
    .I_CH0_RFIFONUM(gmem0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem0_BVALID),
    .I_CH0_BREADY(1'b0)
);

ldl_dsolve_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read2_U0_m_axi_gmem1_ARVALID),
    .I_CH0_ARREADY(gmem1_ARREADY),
    .I_CH0_ARADDR(read2_U0_m_axi_gmem1_ARADDR),
    .I_CH0_ARLEN(read2_U0_m_axi_gmem1_ARLEN),
    .I_CH0_RVALID(gmem1_RVALID),
    .I_CH0_RREADY(read2_U0_m_axi_gmem1_RREADY),
    .I_CH0_RDATA(gmem1_RDATA),
    .I_CH0_RFIFONUM(gmem1_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem1_BVALID),
    .I_CH0_BREADY(1'b0)
);

ldl_dsolve_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem2_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem2_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem2_RDATA),
    .I_CH0_RFIFONUM(gmem2_RFIFONUM),
    .I_CH0_AWVALID(writeout_U0_m_axi_gmem2_AWVALID),
    .I_CH0_AWREADY(gmem2_AWREADY),
    .I_CH0_AWADDR(writeout_U0_m_axi_gmem2_AWADDR),
    .I_CH0_AWLEN(writeout_U0_m_axi_gmem2_AWLEN),
    .I_CH0_WVALID(writeout_U0_m_axi_gmem2_WVALID),
    .I_CH0_WREADY(gmem2_WREADY),
    .I_CH0_WDATA(writeout_U0_m_axi_gmem2_WDATA),
    .I_CH0_WSTRB(writeout_U0_m_axi_gmem2_WSTRB),
    .I_CH0_BVALID(gmem2_BVALID),
    .I_CH0_BREADY(writeout_U0_m_axi_gmem2_BREADY)
);

ldl_dsolve_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_writeout_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .out_r(out_r),
    .out_r_c_din(entry_proc_U0_out_r_c_din),
    .out_r_c_num_data_valid(out_r_c_num_data_valid),
    .out_r_c_fifo_cap(out_r_c_fifo_cap),
    .out_r_c_full_n(out_r_c_full_n),
    .out_r_c_write(entry_proc_U0_out_r_c_write)
);

ldl_dsolve_read1 read1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read1_U0_ap_start),
    .start_full_n(start_for_compute_U0_full_n),
    .ap_done(read1_U0_ap_done),
    .ap_continue(read1_U0_ap_continue),
    .ap_idle(read1_U0_ap_idle),
    .ap_ready(read1_U0_ap_ready),
    .start_out(read1_U0_start_out),
    .start_write(read1_U0_start_write),
    .n(n),
    .m_axi_gmem0_AWVALID(read1_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(read1_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(read1_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(read1_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(read1_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(read1_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(read1_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(read1_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(read1_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(read1_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(read1_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(read1_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(read1_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(read1_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(read1_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(read1_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(read1_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(read1_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(read1_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(read1_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(read1_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(read1_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(read1_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(read1_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(read1_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(read1_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(read1_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(read1_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(read1_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(read1_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(read1_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(read1_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .X(X),
    .X_stream_din(read1_U0_X_stream_din),
    .X_stream_num_data_valid(X_stream_num_data_valid),
    .X_stream_fifo_cap(X_stream_fifo_cap),
    .X_stream_full_n(X_stream_full_n),
    .X_stream_write(read1_U0_X_stream_write),
    .n_c1_din(read1_U0_n_c1_din),
    .n_c1_num_data_valid(n_c1_num_data_valid),
    .n_c1_fifo_cap(n_c1_fifo_cap),
    .n_c1_full_n(n_c1_full_n),
    .n_c1_write(read1_U0_n_c1_write)
);

ldl_dsolve_read2 read2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read2_U0_ap_start),
    .ap_done(read2_U0_ap_done),
    .ap_continue(read2_U0_ap_continue),
    .ap_idle(read2_U0_ap_idle),
    .ap_ready(read2_U0_ap_ready),
    .n(n),
    .m_axi_gmem1_AWVALID(read2_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(read2_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(read2_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(read2_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(read2_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(read2_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(read2_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(read2_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(read2_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(read2_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(read2_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(read2_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(read2_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(read2_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(read2_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(read2_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(read2_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(read2_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(read2_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(read2_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(read2_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(read2_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(read2_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(read2_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(read2_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(read2_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(read2_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(read2_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(read2_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(read2_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(read2_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(read2_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .D(D),
    .D_stream_din(read2_U0_D_stream_din),
    .D_stream_num_data_valid(D_stream_num_data_valid),
    .D_stream_fifo_cap(D_stream_fifo_cap),
    .D_stream_full_n(D_stream_full_n),
    .D_stream_write(read2_U0_D_stream_write)
);

ldl_dsolve_compute compute_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_U0_ap_start),
    .ap_done(compute_U0_ap_done),
    .ap_continue(compute_U0_ap_continue),
    .ap_idle(compute_U0_ap_idle),
    .ap_ready(compute_U0_ap_ready),
    .n_dout(n_c1_dout),
    .n_num_data_valid(n_c1_num_data_valid),
    .n_fifo_cap(n_c1_fifo_cap),
    .n_empty_n(n_c1_empty_n),
    .n_read(compute_U0_n_read),
    .X_stream_dout(X_stream_dout),
    .X_stream_num_data_valid(X_stream_num_data_valid),
    .X_stream_fifo_cap(X_stream_fifo_cap),
    .X_stream_empty_n(X_stream_empty_n),
    .X_stream_read(compute_U0_X_stream_read),
    .D_stream_dout(D_stream_dout),
    .D_stream_num_data_valid(D_stream_num_data_valid),
    .D_stream_fifo_cap(D_stream_fifo_cap),
    .D_stream_empty_n(D_stream_empty_n),
    .D_stream_read(compute_U0_D_stream_read),
    .X2_stream_din(compute_U0_X2_stream_din),
    .X2_stream_num_data_valid(X2_stream_num_data_valid),
    .X2_stream_fifo_cap(X2_stream_fifo_cap),
    .X2_stream_full_n(X2_stream_full_n),
    .X2_stream_write(compute_U0_X2_stream_write),
    .n_c_din(compute_U0_n_c_din),
    .n_c_num_data_valid(n_c_num_data_valid),
    .n_c_fifo_cap(n_c_fifo_cap),
    .n_c_full_n(n_c_full_n),
    .n_c_write(compute_U0_n_c_write)
);

ldl_dsolve_writeout writeout_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(writeout_U0_ap_start),
    .ap_done(writeout_U0_ap_done),
    .ap_continue(writeout_U0_ap_continue),
    .ap_idle(writeout_U0_ap_idle),
    .ap_ready(writeout_U0_ap_ready),
    .n_dout(n_c_dout),
    .n_num_data_valid(n_c_num_data_valid),
    .n_fifo_cap(n_c_fifo_cap),
    .n_empty_n(n_c_empty_n),
    .n_read(writeout_U0_n_read),
    .X2_stream_dout(X2_stream_dout),
    .X2_stream_num_data_valid(X2_stream_num_data_valid),
    .X2_stream_fifo_cap(X2_stream_fifo_cap),
    .X2_stream_empty_n(X2_stream_empty_n),
    .X2_stream_read(writeout_U0_X2_stream_read),
    .m_axi_gmem2_AWVALID(writeout_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(writeout_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(writeout_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(writeout_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(writeout_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(writeout_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(writeout_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(writeout_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(writeout_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(writeout_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(writeout_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(writeout_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(writeout_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(gmem2_WREADY),
    .m_axi_gmem2_WDATA(writeout_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(writeout_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(writeout_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(writeout_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(writeout_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(writeout_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(writeout_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(writeout_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(writeout_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(writeout_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(writeout_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(writeout_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(writeout_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(writeout_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(writeout_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(writeout_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(writeout_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(writeout_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(128'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(9'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(gmem2_BVALID),
    .m_axi_gmem2_BREADY(writeout_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(gmem2_BRESP),
    .m_axi_gmem2_BID(gmem2_BID),
    .m_axi_gmem2_BUSER(gmem2_BUSER),
    .X_final_dout(out_r_c_dout),
    .X_final_num_data_valid(out_r_c_num_data_valid),
    .X_final_fifo_cap(out_r_c_fifo_cap),
    .X_final_empty_n(out_r_c_empty_n),
    .X_final_read(writeout_U0_X_final_read)
);

ldl_dsolve_fifo_w64_d4_S out_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_out_r_c_din),
    .if_full_n(out_r_c_full_n),
    .if_write(entry_proc_U0_out_r_c_write),
    .if_dout(out_r_c_dout),
    .if_num_data_valid(out_r_c_num_data_valid),
    .if_fifo_cap(out_r_c_fifo_cap),
    .if_empty_n(out_r_c_empty_n),
    .if_read(writeout_U0_X_final_read)
);

ldl_dsolve_fifo_w128_d3_S X_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read1_U0_X_stream_din),
    .if_full_n(X_stream_full_n),
    .if_write(read1_U0_X_stream_write),
    .if_dout(X_stream_dout),
    .if_num_data_valid(X_stream_num_data_valid),
    .if_fifo_cap(X_stream_fifo_cap),
    .if_empty_n(X_stream_empty_n),
    .if_read(compute_U0_X_stream_read)
);

ldl_dsolve_fifo_w32_d2_S n_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read1_U0_n_c1_din),
    .if_full_n(n_c1_full_n),
    .if_write(read1_U0_n_c1_write),
    .if_dout(n_c1_dout),
    .if_num_data_valid(n_c1_num_data_valid),
    .if_fifo_cap(n_c1_fifo_cap),
    .if_empty_n(n_c1_empty_n),
    .if_read(compute_U0_n_read)
);

ldl_dsolve_fifo_w128_d3_S D_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read2_U0_D_stream_din),
    .if_full_n(D_stream_full_n),
    .if_write(read2_U0_D_stream_write),
    .if_dout(D_stream_dout),
    .if_num_data_valid(D_stream_num_data_valid),
    .if_fifo_cap(D_stream_fifo_cap),
    .if_empty_n(D_stream_empty_n),
    .if_read(compute_U0_D_stream_read)
);

ldl_dsolve_fifo_w128_d2_S X2_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_U0_X2_stream_din),
    .if_full_n(X2_stream_full_n),
    .if_write(compute_U0_X2_stream_write),
    .if_dout(X2_stream_dout),
    .if_num_data_valid(X2_stream_num_data_valid),
    .if_fifo_cap(X2_stream_fifo_cap),
    .if_empty_n(X2_stream_empty_n),
    .if_read(writeout_U0_X2_stream_read)
);

ldl_dsolve_fifo_w32_d2_S n_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_U0_n_c_din),
    .if_full_n(n_c_full_n),
    .if_write(compute_U0_n_c_write),
    .if_dout(n_c_dout),
    .if_num_data_valid(n_c_num_data_valid),
    .if_fifo_cap(n_c_fifo_cap),
    .if_empty_n(n_c_empty_n),
    .if_read(writeout_U0_n_read)
);

ldl_dsolve_start_for_writeout_U0 start_for_writeout_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_writeout_U0_din),
    .if_full_n(start_for_writeout_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_writeout_U0_dout),
    .if_empty_n(start_for_writeout_U0_empty_n),
    .if_read(writeout_U0_ap_ready)
);

ldl_dsolve_start_for_compute_U0 start_for_compute_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_U0_din),
    .if_full_n(start_for_compute_U0_full_n),
    .if_write(read1_U0_start_write),
    .if_dout(start_for_compute_U0_dout),
    .if_empty_n(start_for_compute_U0_empty_n),
    .if_read(compute_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read1_U0_ap_ready <= ap_sync_read1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read2_U0_ap_ready <= ap_sync_read2_U0_ap_ready;
        end
    end
end

assign ap_done = writeout_U0_ap_done;

assign ap_idle = (writeout_U0_ap_idle & read2_U0_ap_idle & read1_U0_ap_idle & entry_proc_U0_ap_idle & compute_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_read1_U0_ap_ready = (read1_U0_ap_ready | ap_sync_reg_read1_U0_ap_ready);

assign ap_sync_read2_U0_ap_ready = (read2_U0_ap_ready | ap_sync_reg_read2_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read2_U0_ap_ready & ap_sync_read1_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign compute_U0_ap_continue = 1'b1;

assign compute_U0_ap_start = start_for_compute_U0_empty_n;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem0_RID = 1'd0;

assign gmem0_RLAST = 1'b0;

assign gmem0_RRESP = 2'd0;

assign gmem0_RUSER = 1'd0;

assign gmem1_RID = 1'd0;

assign gmem1_RLAST = 1'b0;

assign gmem1_RRESP = 2'd0;

assign gmem1_RUSER = 1'd0;

assign gmem2_BID = 1'd0;

assign gmem2_BRESP = 2'd0;

assign gmem2_BUSER = 1'd0;

assign read1_U0_ap_continue = 1'b1;

assign read1_U0_ap_start = ((ap_sync_reg_read1_U0_ap_ready ^ 1'b1) & ap_start);

assign read2_U0_ap_continue = 1'b1;

assign read2_U0_ap_start = ((ap_sync_reg_read2_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_compute_U0_din = 1'b1;

assign start_for_writeout_U0_din = 1'b1;

assign writeout_U0_ap_continue = 1'b1;

assign writeout_U0_ap_start = start_for_writeout_U0_empty_n;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "ldl_dsolve_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //ldl_dsolve

