// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ldl_dsolve_read1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        X,
        X_stream_din,
        X_stream_num_data_valid,
        X_stream_fifo_cap,
        X_stream_full_n,
        X_stream_write,
        n_c1_din,
        n_c1_num_data_valid,
        n_c1_fifo_cap,
        n_c1_full_n,
        n_c1_write
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [127:0] m_axi_gmem0_WDATA;
output  [15:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [127:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] X;
output  [127:0] X_stream_din;
input  [2:0] X_stream_num_data_valid;
input  [2:0] X_stream_fifo_cap;
input   X_stream_full_n;
output   X_stream_write;
output  [31:0] n_c1_din;
input  [2:0] n_c1_num_data_valid;
input  [2:0] n_c1_fifo_cap;
input   n_c1_full_n;
output   n_c1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem0_ARVALID;
reg[63:0] m_axi_gmem0_ARADDR;
reg[0:0] m_axi_gmem0_ARID;
reg[31:0] m_axi_gmem0_ARLEN;
reg[2:0] m_axi_gmem0_ARSIZE;
reg[1:0] m_axi_gmem0_ARBURST;
reg[1:0] m_axi_gmem0_ARLOCK;
reg[3:0] m_axi_gmem0_ARCACHE;
reg[2:0] m_axi_gmem0_ARPROT;
reg[3:0] m_axi_gmem0_ARQOS;
reg[3:0] m_axi_gmem0_ARREGION;
reg[0:0] m_axi_gmem0_ARUSER;
reg m_axi_gmem0_RREADY;
reg X_stream_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    n_c1_blk_n;
wire   [31:0] div_fu_152_p3;
reg   [31:0] div_reg_203;
reg    ap_block_state1;
wire   [29:0] empty_fu_170_p3;
reg   [29:0] empty_reg_208;
wire  signed [59:0] trunc_ln_fu_178_p4;
reg   [59:0] trunc_ln_reg_213;
wire   [63:0] zext_ln15_fu_199_p1;
wire    grp_read1_Pipeline_read_fu_94_ap_start;
wire    grp_read1_Pipeline_read_fu_94_ap_done;
wire    grp_read1_Pipeline_read_fu_94_ap_idle;
wire    grp_read1_Pipeline_read_fu_94_ap_ready;
wire    grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWVALID;
wire   [63:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWADDR;
wire   [0:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWID;
wire   [31:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLEN;
wire   [2:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWBURST;
wire   [1:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWPROT;
wire   [3:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWQOS;
wire   [3:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWREGION;
wire   [0:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWUSER;
wire    grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WVALID;
wire   [127:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WDATA;
wire   [15:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WSTRB;
wire    grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WLAST;
wire   [0:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WID;
wire   [0:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WUSER;
wire    grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID;
wire   [63:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR;
wire   [0:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID;
wire   [31:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN;
wire   [2:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST;
wire   [1:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT;
wire   [3:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS;
wire   [3:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION;
wire   [0:0] grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER;
wire    grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY;
wire    grp_read1_Pipeline_read_fu_94_m_axi_gmem0_BREADY;
wire   [127:0] grp_read1_Pipeline_read_fu_94_X_stream_din;
wire    grp_read1_Pipeline_read_fu_94_X_stream_write;
reg    grp_read1_Pipeline_read_fu_94_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [63:0] sext_ln15_fu_188_p1;
reg    n_c1_write_local;
wire   [31:0] p_neg_fu_112_p2;
wire   [30:0] p_lshr_fu_118_p4;
wire   [31:0] p_lshr_cast_fu_128_p1;
wire   [30:0] p_lshr_f_fu_138_p4;
wire   [0:0] tmp_fu_104_p3;
wire   [31:0] p_neg_t_fu_132_p2;
wire   [31:0] p_lshr_f_cast_fu_148_p1;
wire   [0:0] icmp_ln15_fu_160_p2;
wire   [29:0] trunc_ln15_fu_166_p1;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_read1_Pipeline_read_fu_94_ap_start_reg = 1'b0;
end

ldl_dsolve_read1_Pipeline_read grp_read1_Pipeline_read_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_read1_Pipeline_read_fu_94_ap_start),
    .ap_done(grp_read1_Pipeline_read_fu_94_ap_done),
    .ap_idle(grp_read1_Pipeline_read_fu_94_ap_idle),
    .ap_ready(grp_read1_Pipeline_read_fu_94_ap_ready),
    .m_axi_gmem0_AWVALID(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .X_stream_din(grp_read1_Pipeline_read_fu_94_X_stream_din),
    .X_stream_num_data_valid(3'd0),
    .X_stream_fifo_cap(3'd0),
    .X_stream_full_n(X_stream_full_n),
    .X_stream_write(grp_read1_Pipeline_read_fu_94_X_stream_write),
    .div(div_reg_203),
    .sext_ln15(trunc_ln_reg_213)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state11) & (grp_read1_Pipeline_read_fu_94_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_read1_Pipeline_read_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_read1_Pipeline_read_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_read1_Pipeline_read_fu_94_ap_ready == 1'b1)) begin
            grp_read1_Pipeline_read_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        div_reg_203 <= div_fu_152_p3;
        empty_reg_208 <= empty_fu_170_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln_reg_213 <= {{X[63:4]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        X_stream_write = grp_read1_Pipeline_read_fu_94_X_stream_write;
    end else begin
        X_stream_write = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_read1_Pipeline_read_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_read1_Pipeline_read_fu_94_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_read1_Pipeline_read_fu_94_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARADDR = sext_ln15_fu_188_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARADDR = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR;
    end else begin
        m_axi_gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARBURST = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST;
    end else begin
        m_axi_gmem0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARCACHE = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE;
    end else begin
        m_axi_gmem0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARID = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID;
    end else begin
        m_axi_gmem0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARLEN = zext_ln15_fu_199_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARLEN = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN;
    end else begin
        m_axi_gmem0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARLOCK = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK;
    end else begin
        m_axi_gmem0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARPROT = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT;
    end else begin
        m_axi_gmem0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARQOS = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS;
    end else begin
        m_axi_gmem0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARREGION = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION;
    end else begin
        m_axi_gmem0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARSIZE = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE;
    end else begin
        m_axi_gmem0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARUSER = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER;
    end else begin
        m_axi_gmem0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_ARVALID = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_RREADY = grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_c1_blk_n = n_c1_full_n;
    end else begin
        n_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        n_c1_write_local = 1'b1;
    end else begin
        n_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_read1_Pipeline_read_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_stream_din = grp_read1_Pipeline_read_fu_94_X_stream_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (n_c1_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign div_fu_152_p3 = ((tmp_fu_104_p3[0:0] == 1'b1) ? p_neg_t_fu_132_p2 : p_lshr_f_cast_fu_148_p1);

assign empty_fu_170_p3 = ((icmp_ln15_fu_160_p2[0:0] == 1'b1) ? trunc_ln15_fu_166_p1 : 30'd0);

assign grp_read1_Pipeline_read_fu_94_ap_start = grp_read1_Pipeline_read_fu_94_ap_start_reg;

assign icmp_ln15_fu_160_p2 = (($signed(p_lshr_f_fu_138_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 128'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 16'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign n_c1_din = n;

assign n_c1_write = n_c1_write_local;

assign p_lshr_cast_fu_128_p1 = p_lshr_fu_118_p4;

assign p_lshr_f_cast_fu_148_p1 = p_lshr_f_fu_138_p4;

assign p_lshr_f_fu_138_p4 = {{n[31:1]}};

assign p_lshr_fu_118_p4 = {{p_neg_fu_112_p2[31:1]}};

assign p_neg_fu_112_p2 = (32'd0 - n);

assign p_neg_t_fu_132_p2 = (32'd0 - p_lshr_cast_fu_128_p1);

assign sext_ln15_fu_188_p1 = trunc_ln_fu_178_p4;

assign start_out = real_start;

assign tmp_fu_104_p3 = n[32'd31];

assign trunc_ln15_fu_166_p1 = div_fu_152_p3[29:0];

assign trunc_ln_fu_178_p4 = {{X[63:4]}};

assign zext_ln15_fu_199_p1 = empty_reg_208;

endmodule //ldl_dsolve_read1
