-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ldl_dsolve_read1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    n : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    X : IN STD_LOGIC_VECTOR (63 downto 0);
    X_stream_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    X_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    X_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    X_stream_full_n : IN STD_LOGIC;
    X_stream_write : OUT STD_LOGIC;
    n_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    n_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    n_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    n_c1_full_n : IN STD_LOGIC;
    n_c1_write : OUT STD_LOGIC );
end;


architecture behav of ldl_dsolve_read1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal gmem0_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal n_c1_blk_n : STD_LOGIC;
    signal div_fu_152_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal div_reg_203 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal empty_fu_170_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_reg_208 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln_fu_178_p4 : STD_LOGIC_VECTOR (59 downto 0);
    signal trunc_ln_reg_213 : STD_LOGIC_VECTOR (59 downto 0);
    signal zext_ln15_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read1_Pipeline_read_fu_94_ap_start : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_ap_done : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_ap_idle : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_ap_ready : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_X_stream_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_read1_Pipeline_read_fu_94_X_stream_write : STD_LOGIC;
    signal grp_read1_Pipeline_read_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal sext_ln15_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_c1_write_local : STD_LOGIC;
    signal p_neg_fu_112_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_fu_118_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_lshr_cast_fu_128_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_f_fu_138_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_104_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t_fu_132_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_f_cast_fu_148_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln15_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln15_fu_166_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ldl_dsolve_read1_Pipeline_read IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        X_stream_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        X_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        X_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        X_stream_full_n : IN STD_LOGIC;
        X_stream_write : OUT STD_LOGIC;
        div : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln15 : IN STD_LOGIC_VECTOR (59 downto 0) );
    end component;



begin
    grp_read1_Pipeline_read_fu_94 : component ldl_dsolve_read1_Pipeline_read
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read1_Pipeline_read_fu_94_ap_start,
        ap_done => grp_read1_Pipeline_read_fu_94_ap_done,
        ap_idle => grp_read1_Pipeline_read_fu_94_ap_idle,
        ap_ready => grp_read1_Pipeline_read_fu_94_ap_ready,
        m_axi_gmem0_AWVALID => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => grp_read1_Pipeline_read_fu_94_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        X_stream_din => grp_read1_Pipeline_read_fu_94_X_stream_din,
        X_stream_num_data_valid => ap_const_lv3_0,
        X_stream_fifo_cap => ap_const_lv3_0,
        X_stream_full_n => X_stream_full_n,
        X_stream_write => grp_read1_Pipeline_read_fu_94_X_stream_write,
        div => div_reg_203,
        sext_ln15 => trunc_ln_reg_213);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_read1_Pipeline_read_fu_94_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_read1_Pipeline_read_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read1_Pipeline_read_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_read1_Pipeline_read_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read1_Pipeline_read_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_read1_Pipeline_read_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                div_reg_203 <= div_fu_152_p3;
                empty_reg_208 <= empty_fu_170_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_gmem0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln_reg_213 <= X(63 downto 4);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem0_ARREADY, ap_CS_fsm_state2, ap_block_state1, grp_read1_Pipeline_read_fu_94_ap_done, ap_CS_fsm_state11)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((m_axi_gmem0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_read1_Pipeline_read_fu_94_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    X_stream_din <= grp_read1_Pipeline_read_fu_94_X_stream_din;

    X_stream_write_assign_proc : process(grp_read1_Pipeline_read_fu_94_X_stream_write, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            X_stream_write <= grp_read1_Pipeline_read_fu_94_X_stream_write;
        else 
            X_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_read1_Pipeline_read_fu_94_ap_done)
    begin
        if ((grp_read1_Pipeline_read_fu_94_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(m_axi_gmem0_ARREADY)
    begin
        if ((m_axi_gmem0_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, n_c1_full_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (n_c1_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_read1_Pipeline_read_fu_94_ap_done, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_read1_Pipeline_read_fu_94_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    div_fu_152_p3 <= 
        p_neg_t_fu_132_p2 when (tmp_fu_104_p3(0) = '1') else 
        p_lshr_f_cast_fu_148_p1;
    empty_fu_170_p3 <= 
        trunc_ln15_fu_166_p1 when (icmp_ln15_fu_160_p2(0) = '1') else 
        ap_const_lv30_0;

    gmem0_blk_n_AR_assign_proc : process(m_axi_gmem0_ARREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            gmem0_blk_n_AR <= m_axi_gmem0_ARREADY;
        else 
            gmem0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;

    grp_read1_Pipeline_read_fu_94_ap_start <= grp_read1_Pipeline_read_fu_94_ap_start_reg;
    icmp_ln15_fu_160_p2 <= "1" when (signed(p_lshr_f_fu_138_p4) > signed(ap_const_lv31_0)) else "0";

    internal_ap_ready_assign_proc : process(grp_read1_Pipeline_read_fu_94_ap_done, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_read1_Pipeline_read_fu_94_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_ARADDR_assign_proc : process(m_axi_gmem0_ARREADY, ap_CS_fsm_state2, grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR, ap_CS_fsm_state10, ap_CS_fsm_state11, sext_ln15_fu_188_p1)
    begin
        if (((m_axi_gmem0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARADDR <= sext_ln15_fu_188_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARADDR <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARADDR;
        else 
            m_axi_gmem0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_ARBURST_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARBURST <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARBURST;
        else 
            m_axi_gmem0_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem0_ARCACHE_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARCACHE <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARCACHE;
        else 
            m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem0_ARID_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARID <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARID;
        else 
            m_axi_gmem0_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem0_ARLEN_assign_proc : process(m_axi_gmem0_ARREADY, ap_CS_fsm_state2, zext_ln15_fu_199_p1, grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((m_axi_gmem0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARLEN <= zext_ln15_fu_199_p1(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARLEN <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLEN;
        else 
            m_axi_gmem0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_ARLOCK_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARLOCK <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARLOCK;
        else 
            m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem0_ARPROT_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARPROT <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARPROT;
        else 
            m_axi_gmem0_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem0_ARQOS_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARQOS <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARQOS;
        else 
            m_axi_gmem0_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem0_ARREGION_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARREGION <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARREGION;
        else 
            m_axi_gmem0_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem0_ARSIZE_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARSIZE <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARSIZE;
        else 
            m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem0_ARUSER_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARUSER <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARUSER;
        else 
            m_axi_gmem0_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem0_ARVALID_assign_proc : process(m_axi_gmem0_ARREADY, ap_CS_fsm_state2, grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((m_axi_gmem0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_ARVALID <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_ARVALID;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_gmem0_RREADY <= grp_read1_Pipeline_read_fu_94_m_axi_gmem0_RREADY;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv128_lc_1;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv16_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;

    n_c1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, n_c1_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            n_c1_blk_n <= n_c1_full_n;
        else 
            n_c1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    n_c1_din <= n;
    n_c1_write <= n_c1_write_local;

    n_c1_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            n_c1_write_local <= ap_const_logic_1;
        else 
            n_c1_write_local <= ap_const_logic_0;
        end if; 
    end process;

    p_lshr_cast_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_fu_118_p4),32));
    p_lshr_f_cast_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_f_fu_138_p4),32));
    p_lshr_f_fu_138_p4 <= n(31 downto 1);
    p_lshr_fu_118_p4 <= p_neg_fu_112_p2(31 downto 1);
    p_neg_fu_112_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(n));
    p_neg_t_fu_132_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(p_lshr_cast_fu_128_p1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln15_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_178_p4),64));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_104_p3 <= n(31 downto 31);
    trunc_ln15_fu_166_p1 <= div_fu_152_p3(30 - 1 downto 0);
    trunc_ln_fu_178_p4 <= X(63 downto 4);
    zext_ln15_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_208),64));
end behav;
